name: gardentale
favicon: null
layout_spectrum: 0.6299202782101929
typography_spectrum: 0.6200424851849675
title: Garden Tale - The process of building our garden.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.18288359558209777
  lightness: 0.8767648688517511
  saturation: 0.9907255680300295
  rhythmicContrast: 0.7195439981296659
purpose: []
